export const CURRENT_POSTS_LOADED_SUCCESSFULLY = "CURRENT_POSTS_LOADED_SUCCESSFULLY";
export const CURRENT_POSTS_LOADED_SUCCESSFULLY_AFTER_INITIAL_LOAD = "CURRENT_POSTS_LOADED_SUCCESSFULLY_AFTER_INITIAL_LOAD";
export const CURRENT_POSTS_ARE_LOADING = "CURRENT_POSTS_ARE_LOADING";
export const CURRENT_POSTS_FAILED_LOADING = "CURRENT_POSTS_FAILED_LOADING";

export const INCREASE_NUMBER_OF_LIKES_FOR_A_POST = "INCREASE_NUMBER_OF_LIKES_FOR_A_POST";