export const CURRENT_POSTS_LOADED_SUCCESSFULLY = "CURRENT_POSTS_LOADED_SUCCESSFULLY";
export const CURRENT_POSTS_ARE_LOADING = "CURRENT_POSTS_ARE_LOADING";
export const CURRENT_POSTS_FAILED_LOADING = "CURRENT_POSTS_FAILED_LOADING";